import "@/app/globals.css";
import { cookies } from "next/headers";
import Header from "@/components/Header";
import NextLoader from "@/components/NextTopLoader";
import { Geist, Geist_Mono } from "next/font/google";
import { SnackbarProvider } from "@/components/Snackbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "islamic-research",
  description: "Generated by create next app",
};

export default async function RootLayout(props) {
  const { children } = props;
  const params = await props.params;
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "light";



  return (

    <html data-theme={theme}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <NextLoader />
        <SnackbarProvider>
          <Header initialTheme={theme} />
          {children}
        </SnackbarProvider>
      </body>
    </html>

  );
}
