const routeTitleMap = {
  "/": "mainHeading",
  "/tarjumaQuran": "quran",
  "/azkar": "azkar",
  "/namaz": "namaz",
  "/namaz/1": "namaztitle1",
  "/namaz/2": "namaztitle2",
  "/namaz/3": "namaztitle3",
  "/namaz/4": "namaztitle4",
  "/namaz/5": "namaztitle5",
  "/namaz/6": "namaztitle6",
  "/dua": "dua",
  "/dua/1": "duatitle1",
  "/dua/2": "duatitle2",
  "/dua/3": "duatitle3",
  "/dua/4": "duatitle4",
  "/dua/5": "duatitle5",
  "/dua/6": "duatitle6",
  "/dua/7": "duatitle7",
  "/dua/8": "duatitle8",
  "/dua/9": "duatitle9",
  "/dua/10": "duatitle10",
  "/dua/11": "duatitle11",
  "/dua/12": "duatitle12",
  "/dua/13": "duatitle13",
  "/dua/14": "duatitle14",
  "/dua/15": "duatitle15",
  "/dua/16": "duatitle16",
  "/dua/17": "duatitle17",
  "/dua/18": "duatitle18",
  "/dua/19": "duatitle19",
  "/dua/20": "duatitle20",
  "/dua/21": "duatitle21",
  "/wealth": "wealth",
  "/wealth/1": "wealthtitle1",
  "/wealth/2": "wealthtitle2",
  "/wealth/3": "wealthtitle3",
  "/qayamat": "qayamat",
  "/arshShade": "shadow",
  "/chosenOnes": "chosenOnes",
  "/qabar": "qabar",
};

export default routeTitleMap;
